### ISSUE TITLE
segment_ga4 doesn't allow multiple dynamic segments

### ISSUE THREAD

**Issue by Iuiu1234** [MarkEdmondson1234/googleAnalyticsR#239] opened 2019-03-04 15:53 UTC
segment_ga4 doesn't allow multiple dynamic segments.
But when pass manually as a list to make_ga_4_req. Functions works.

This function
`segment_ga4_mult = function(segments) {
  if(class(segments) != 'list') 
    stop()
  segments.out = lapply( segments, as.list)
  segments.out = do.call(c,segments.out)
  class(segments.out) = 'segment_ga4'
  segments.out
  }`

solves the issue. But I think should be integrated directly to segment_ga4.

## Actual output

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

## 'API Data failed to parse' diagnostics

If you have an error starting with:

`API Data failed to parse.`

* Please install googleAuthR >v0.7.9000:

```r
remotes::install_github("MarkEdmondson1234/googleAuthR")
```

* Restart the R session and run your bugged code.
* It should write a file called `gar_parse_error.rds` to your working directory.
* Run the below to output some diagnostic information and paste the response here.

```r
googleAuthR::gar_debug_parsing("gar_parse_error.rds")
```

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed

**Comment by MarkEdmondson1234** [comment] 2019-09-06 13:06
Thanks, duplicate of https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/253 where there is a work around, and will work on a fix

**Closed by MarkEdmondson1234** 2019-09-06 13:06 UTC
Labels: bug
