### ISSUE TITLE
segments with the condition "ends with"

### ISSUE THREAD

**Issue by stavrovskaya** [MarkEdmondson1234/googleAnalyticsR#195] opened 2018-09-05 10:21 UTC
## What goes wrong
Hi, I use segments for data selection. I need to select sessions, during which users started make order (page ends with personal/order/make/). I use regular expressin for that. But the responce contains sessions with visits of "thank you" pages (ends with personal/order/make/?ORDER_ID=32396). Moreover using equivalent regular expressions gives different result (It looks like in some cases only a part of result is loaded).

## Steps to reproduce the problem
###Variant1:
```
 options(googleAuthR.verbose=2)
 seg_def <- "sessions::condition::ga:pagePath=~.*personal/order/make/$"
 my_segment <- segment_ga4("order",
                             segment_id = seg_def)
 order<-google_analytics(ga_view_id,
                           date_range = c(date_start, date_end), 
                           metrics = c("avgSessionDuration"), 
                           dimensions = c("dimension1", "dateHourMinute", "sourceMedium","dimension2", "pagePath"), 
                           anti_sample = TRUE, segments = my_segment)
```
2018-09-05 13:13:28> anti_sample set to TRUE. Mitigating sampling via multiple API calls.
2018-09-05 13:13:28> Finding how much sampling in data request...
2018-09-05 13:13:28> Calling APIv4....
2018-09-05 13:13:28> Single v4 batch
2018-09-05 13:13:28> Skipping token checks as using cache
2018-09-05 13:13:28> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2018-09-05 13:13:28> Reading cache
2018-09-05 13:13:28> Downloaded [10] rows from a total of [37184].
2018-09-05 13:13:28> No sampling found, returning call
2018-09-05 13:13:28> Calling APIv4....
2018-09-05 13:13:28> Single v4 batch
2018-09-05 13:13:28> Skipping token checks as using cache
2018-09-05 13:13:28> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2018-09-05 13:13:28> Reading cache
2018-09-05 13:13:28> Downloaded [10000] rows from a total of [37184].
2018-09-05 13:13:28> Calling APIv4....
2018-09-05 13:13:28> Single v4 batch
2018-09-05 13:13:28> Skipping token checks as using cache
2018-09-05 13:13:28> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2018-09-05 13:13:28> Reading cache
2018-09-05 13:13:29> Downloaded [27184] rows from a total of [37184].
2018-09-05 13:13:29> All data downloaded, total of [37184] - download time: 0.6861749 secs
> 
###Variant2:
```
 options(googleAuthR.verbose=2)
 seg_def <- "sessions::condition::ga:pagePath=~\\Qpersonal/order/make/\\E$"
 my_segment <- segment_ga4("order",
                             segment_id = seg_def)
 order<-google_analytics(ga_view_id,
                           date_range = c(date_start, date_end), 
                           metrics = c("avgSessionDuration"), 
                           dimensions = c("dimension1", "dateHourMinute", "sourceMedium","dimension2", "pagePath"), 
                           anti_sample = TRUE, segments = my_segment)
```
2018-09-05 13:14:45> anti_sample set to TRUE. Mitigating sampling via multiple API calls.
2018-09-05 13:14:45> Finding how much sampling in data request...
2018-09-05 13:14:45> Calling APIv4....
2018-09-05 13:14:45> Single v4 batch
2018-09-05 13:14:45> Skipping token checks as using cache
2018-09-05 13:14:45> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2018-09-05 13:14:45> Reading cache
2018-09-05 13:14:45> Downloaded [10] rows from a total of [37184].
2018-09-05 13:14:45> No sampling found, returning call
2018-09-05 13:14:45> Calling APIv4....
2018-09-05 13:14:45> Single v4 batch
2018-09-05 13:14:45> Skipping token checks as using cache
2018-09-05 13:14:45> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2018-09-05 13:14:45> Reading cache
2018-09-05 13:14:45> Downloaded [1860] rows from a total of [1860].

## Expected output
"dimension1" is clientId. I expect to observe at least one visit of page order/make/ per user.

## Actual output
In both cases (variant1 and variant2) I observe user that didn't visit this page, but visited "thank you" page
```
order%>% filter(dimension1=="1125556136.1470471377")
```

             dimension1 dateHourMinute      sourceMedium             dimension2                                            pagePath         segment avgSessionDuration
1 1125556136.1470471377   201807170447 (direct) / (none) 1531792038548.lbsot83t www.perfekto.ru/personal/order/make/?ORDER_ID=32396 Dynamic Segment                  0
2 1125556136.1470471377   201807210018 (direct) / (none) 1532121516499.flf4dod9 www.perfekto.ru/personal/order/make/?ORDER_ID=32396 Dynamic Segment                  0

Before you run your code, please run:

`options(googleAuthR.verbose=2)` and copy-paste the console output here.  
Check it doesn't include any sensitive info like auth tokens or accountIds - you can usually just edit those out manually and replace with say `XXX`

(see above)

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2         ggplot2_3.0.0          dplyr_0.7.6            googleAuthR_0.6.3      googleAnalyticsR_0.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     rstudioapi_0.7   bindr_0.1.1      magrittr_1.5     munsell_0.5.0    tidyselect_0.2.4 colorspace_1.3-2 R6_2.2.2         rlang_0.2.1      plyr_1.8.4      
[11] httr_1.3.1       tools_3.5.1      grid_3.5.1       gtable_0.2.0     withr_2.1.2      lazyeval_0.2.1   yaml_2.1.19      assertthat_0.2.0 digest_0.6.15    tibble_1.4.2    
[21] crayon_1.3.4     purrr_0.2.5      tidyr_0.8.1      curl_3.2         memoise_1.1.0    glue_1.3.0       compiler_3.5.1   pillar_1.3.0     scales_0.5.0     jsonlite_1.5    
[31] pkgconfig_2.0.1

**Comment by MarkEdmondson1234** [comment] 2018-09-05 12:28
This looks like expected behaviour - if you use segments, it will give you all user sessions that had that page in them, plus every other page they visited - is that what you want?  It makes sense that a segment including all order pages would also include all thank you pages as well.

Perhaps you instead want to dimension filter all the pages?  That would be like having a table of all the pagePaths, and then you filter down to just the rows you want (e.g. the order page)

**Comment by stavrovskaya** [comment] 2018-09-06 19:03
Hi, 
This looks like expected behaviour - if you use segments, it will give you all user sessions that had that page in them, plus every other page they visited - is that what you want? 
- Definitely!
It makes sense that a segment including all order pages would also include all thank you pages as well.
- Of course, but for this user it doesn't include order page, only thank you page.
Actually, I have tried the same request in the query explorer (https://ga-dev-tools.appspot.com/query-explorer/) and it gives the same result. I think it is a bug of API. But the question about the number of resulting rows for Variant2 is still actual.

2018-09-05 13:14:45> anti_sample set to TRUE. Mitigating sampling via multiple API calls.
2018-09-05 13:14:45> Finding how much sampling in data request...
2018-09-05 13:14:45> Calling APIv4....
2018-09-05 13:14:45> Single v4 batch
2018-09-05 13:14:45> Skipping token checks as using cache
2018-09-05 13:14:45> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2018-09-05 13:14:45> Reading cache
2018-09-05 13:14:45> Downloaded [10] rows from a total of **[37184]**.
2018-09-05 13:14:45> No sampling found, returning call
2018-09-05 13:14:45> Calling APIv4....
2018-09-05 13:14:45> Single v4 batch
2018-09-05 13:14:45> Skipping token checks as using cache
2018-09-05 13:14:45> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2018-09-05 13:14:45> Reading cache
2018-09-05 13:14:45> Downloaded **[1860]** rows from a total of **[1860]**.

Thank you!

**Comment by MarkEdmondson1234** [comment] 2018-09-08 15:48
I think best strategy would be to try to create the segments in the webUI until they match what you want, then saving it as a custom segment, that you can specify that via its ID rather than code.  As you say, I don't think there is much code I can fix to help here, so I will close the issue, but do let me know if you find a solution.

**Closed by MarkEdmondson1234** 2018-09-08 15:48 UTC

**Comment by stavrovskaya** [comment] 2018-09-09 20:52
![image](https://user-images.githubusercontent.com/19977213/45268816-525bc580-b48b-11e8-8ecd-273537b5ad88.png)
But what about this?
