### ISSUE TITLE
Don't add bigquery looksups if they are NA

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#122] opened 2017-10-16 14:34 UTC
Else it looks for NA in dataset...

**Comment by j450h1** [comment] 2017-12-22 01:18
I can look into this in the new year, if you can provide a reproducible example and the relevant function.

**Comment by j450h1** [comment] 2018-01-17 07:57
Can you elaborate? I work quite a bit with BigQuery, so I think I might be able to resolve this one.

**Comment by MarkEdmondson1234** [comment] 2018-01-17 08:35
This is just that this lookup:

https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/959eeb7ccd8e349211e3a20a1294f0bd933d7e9b/R/bigQuery.R#L232-L270

If a user adds a dimension (or metric) to `google_analytics_bq()` that isn't in the list then the raw SQL has an NA in it instead:

```r
library(googleAnalyticsR)

## this one is ok
google_analytics_bq("blah","foo", start = "2017-01-01", end = "2017-02-01", metrics = "sessions", dimensions = "source", return_query_only = TRUE)
#[1] "SELECT trafficSource.source as source, SUM(totals.visits) as sessions FROM #(TABLE_DATE_RANGE([foo.ga_sessions_], TIMESTAMP('2017-01-01'), TIMESTAMP('2017-02-01'))) #GROUP BY source  LIMIT 100"

## but this one has an NA as adWordsQuery
google_analytics_bq("blah","foo", start = "2017-01-01", end = "2017-02-01", metrics = "sessions", dimensions = "adWordsQuery", return_query_only = TRUE)
[1] "SELECT NA, SUM(totals.visits) as sessions FROM (TABLE_DATE_RANGE([foo.ga_sessions_], TIMESTAMP('2017-01-01'), TIMESTAMP('2017-02-01'))) GROUP BY adWordsQuery  LIMIT 100"
```

It simply needs to raise an error if it has NA I think, and/or add the rest of the dimensions/metrics that are missing.

**Comment by j450h1** [comment] 2018-01-19 03:31
Sure, I will raise an error if the dimension or metric is invalid.

**Comment by j450h1** [comment] 2018-01-19 05:05
I've made the commits. See the latest PR. 

However, I found a bug when no dimension is entered:

``` r
# null dimension
google_analytics_bq("blah","foo", start = "2017-01-01", end = "2017-02-01", metrics = "sessions", return_query_only = TRUE)
#> [1] "SELECT , SUM(totals.visits) as sessions FROM (TABLE_DATE_RANGE([foo.ga_sessions_], TIMESTAMP('2017-01-01'), TIMESTAMP('2017-02-01')))   LIMIT 100"
```
I have also committed the test where I found this, but I do have a solution to throw an error if no dimension provided. Having a NULL metric value is okay. Anyways, I will commit that fix shortly.

**Comment by j450h1** [comment] 2018-01-19 05:12
Oh just to clarify if its not obvious, the query fails due to the additional comma. The other option is to remove the comma somehow since the query will work to give you the total daily sessions (on a side note, I think we should either put a warning somewhere as BQ includes non-interactive sessions in the visits count so there will be a discrepancy or alternatively add a filter to only look at interactive sessions - https://stackoverflow.com/questions/30419771/total-sessions-in-bigquery-vs-google-analytics-reports)

**Comment by j450h1** [comment] 2018-01-19 05:25
The fix is complete with latest commit. On second thought, I think it makes sense to require at least one dimension to avoid confusion and I have suggested at least date in the error message. Anyways, let me know if you have any questions or issues with this.

**Comment by MarkEdmondson1234** [comment] 2018-01-19 12:03
This is great, thanks @j450h1 !  I moved the tests into the test syntax if you are interested to see how it works https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/tests/testthat/test_google_analytics_bq.R

**Closed** 2018-01-19 12:02 UTC
Labels: bug

**Comment by j450h1** [comment] 2018-01-20 00:45
Yes, definitely. Will follow that example in the future.
