### ISSUE TITLE
JSON fetch error: Request had invalid authentication credentials...

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#82] opened 2017-05-26 21:49 UTC
**Code snippet:**

```r
library(googleAnalyticsR)
options(googleAuthR.client_id = [my client ID])
options(googleAuthR.client_secret = [my client secret)
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics")

ga_auth()

foo <- google_analytics_4(viewId = view_id,
                          date_range = c(start_date, end_date),
                          metrics = "pageviews",
                          dimensions = "date")
```

`googleAuthR` is 0.5.1.9000
`googleAnalyticsR` is 0.4.0.9000

When I run this initially -- no problem. Browser opens, I get prompted to provide permission, authentication goes through, script runs fine, .httr-oauth file gets created.

If I *immediately* re-run the script, it works fine. If I wait some period of time -- hard to clock, but it's an hour (or less) and try to re-run the script, I get:

```
Request Status Code: 401
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
Error in error_check(out) : 
  JSON fetch error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```
If I then delete .httr-oauth` and run the script, the browser window is just a message that I've authenticated (I don't have to actually grant permission). And, the script runs fine. And will continue to run fine... until I wait an hour or so.

**Comment by MarkEdmondson1234** [comment] 2017-05-26 22:01
Sounds like the refresh token can't be created - is it possible in the meantime that your R session has restarted and you've lost the client ID/secret/scopes settings you set when authenticating?  They have to be the same otherwise it kicks you out to authenticate again.  You can keep an eye on which file you have authenticated with by running this:

```r
options(googleAuthR.verbose = 2)
googleAuthR::gar_token_info()
```

The data that puts out should be identical each time the auth is trying to connect. (e.g. when `ga_auth()` is run)

**Comment by MarkEdmondson1234** [comment] 2017-05-26 22:06
The script should also set the options before the library loads, as otherwise it will use the default.  that may be the difference as the first time you load/auth, its the default, then second its your options.  All times, it should be in this order:

```r
options(googleAuthR.client_id = [my client ID])
options(googleAuthR.client_secret = [my client secret)
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics")

library(googleAnalyticsR)

ga_auth()

foo <- google_analytics_4(viewId = view_id,
                          date_range = c(start_date, end_date),
                          metrics = "pageviews",
                          dimensions = "date")
```

**Comment by gilliganondata** [comment] 2017-05-27 15:33
I'm thinking the order of setting the options was the root cause. It seems to be working fine once I made that switch. For some reason, I had in my mind that the options were applied at the time of a function call. It now seems totally obvious that the options are applied at the time a library **loads**. Thanks!

**Comment by gilliganondata** [comment] 2017-05-29 14:33
Nevermind... :-(

**Comment by gilliganondata** [comment] 2017-05-31 15:59
Okay... I'm schizophrenic. I thought it was working, but it doesn't seem to be.

```
client_id <- Sys.getenv("GA_CLIENT_ID")
client_secret <- Sys.getenv("GA_CLIENT_SECRET")
options(googleAuthR.client_id = client_id)
options(googleAuthR.client_secret = client_secret)

# I've fiddled with different scopes a bit, but always re-start my R session before 
# re-running the script. And, have gone through the authentication errors, deleted
# .httr-oauth to get things working again... and then had it fail again even after I
# did NOT change the scopes.
options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/analytics",
                                        "https://www.googleapis.com/auth/analytics.readonly"))
options(googleAuthR.verbose = 2)

library(googleAnalyticsR)
library(tidyverse)

# Settings
start_date <- "2017-04-25"
end_date <- as.character(Sys.Date()-1)
view_id <- "[XXXXXXXXX]"
 
# Authorize Google Analytics
ga_auth()
 
foo <- google_analytics_4(viewId = view_id,
                          date_range = c(start_date, end_date),
                          metrics = "pageviews",
                          dimensions = "date")
```
After it works, if I run it again an hour or two later (edits below are the Xs -- I don't think they're material): 

> Hash: c083[...]
> App key: 4088659[... my key -- not the default one]
> Method: new_token
> 2017-05-31 11:50:06> Authenticated
> 2017-05-31 11:50:12> Calling APIv4....
> 2017-05-31 11:50:12> Single v4 batch
> Token exists.
> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:XXXXXXX","dateRanges":[{"startDate":"2017-04-25","endDate":"2017-05-24"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"}],"metrics":[{"expression":"ga:pageviews","alias":"pageviews","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
> Request Status Code: 401
> JSON fetch error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
> No retry attempted: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
> Hash: c0831XXXXX
> App key: 408865XXXXX
> Method: new_token
> Error in checkGoogleAPIError(req) : 
>   JSON fetch error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
> Error in error_check(out) : 
>   JSON fetch error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

That `new_token` thing -- is that a clue? It shouldn't be getting a new token, should it?

**Comment by MarkEdmondson1234** [comment] 2017-05-31 20:07
When you run these lines the first time, can you show those logs?

```r
options(googleAuthR.verbose = 2)

library(googleAnalyticsR)
library(tidyverse)

# Settings
start_date <- "2017-04-25"
end_date <- as.character(Sys.Date()-1)
view_id <- "[XXXXXXXXX]"
 
# Authorize Google Analytics
ga_auth()
```

**Comment by MarkEdmondson1234** [comment] 2017-05-31 20:09
Are you running these lines each time you run the script_
?

```r
options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/analytics",
                                        "https://www.googleapis.com/auth/analytics.readonly"))
```

Probably better off not using them, they are set by the library itself, if not set the same each time may be causing your issue.

**Comment by MarkEdmondson1234** [comment] 2017-05-31 20:16
The logs are also missing the important bits :)

When running `googleAuthR::gar_token_info()` it should say something like this:

```r
**Token cache file: /Users/mark/dev/auth/googleAnalyticsR.httr-oauth
Scopes: https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.readonly**
Hash: d7af62b6f75e8ff47b88d50d6b51c7d8
App key: 289759286325-da3fr5kq4nl4nkhmhs2uft776kdsggbo.apps.googleusercontent.com
Method: filepath
```

**Comment by MarkEdmondson1234** [comment] 2017-05-31 20:26
So yes, the `new_token` flag is there when its re-authenticating, which is when a token hasn't been passed to the authentication token.  By default this is at location `.httr-oauth` - you can check yours with `getOption("googleAuthR.httr_oauth_cache")` - if its `TRUE` then its the above.

I suspect you may have the environment var `GA_AUTH_FILE` set too, which is possibly pointing at a token not authenticated under the correct scopes - could that be the case?  This token would be taken precedence if it was set.

**Comment by gilliganondata** [comment] 2017-06-01 14:29
I removed the scopes option and started a new session.

When it hits the `ga_auth()`, I got a browser and had to explicitly provide permission. This is what the message was:

> Waiting for authentication in browser...
> Press Esc/Ctrl + C to abort
> Authentication complete.
> Hash: d0b64ec51ff2fed03c33bddaa05cabc7
> App key: 408865981365-2hmd6jqjg3ndd07doueh53v1of1hq1ra.apps.googleusercontent.com
> Method: new_token
> 2017-06-01 10:19:06> Authenticated

After it ran and brought back data, I ran `googleAuthR::gar_token_info()`, and this is what I got back:

> Hash: d0b64XXXXXXXXXXXXX
> App key: 408865XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Method: new_token

And, `getOption("googleAuthR.httr_oauth_cache")` returns `TRUE`.

I also ran `Sys.getenv("GA_AUTH_FILE")`, and that simply returned `""`.

I'm not entirely clear how to interpret this. If the `googleAuthR.httr_oauth_cache` option is `TRUE`, then it should be caching and using the `.httr_oauth` file that got created and is present in my working directory, shouldn't it? Is the issue possibly that the `GA_AUTH_FILE` is not set at all? When/what should be setting that?

Thanks for your help (and patience)!

**Comment by MarkEdmondson1234** [comment] 2017-06-03 20:16
> I'm not entirely clear how to interpret this. If the googleAuthR.httr_oauth_cache option is TRUE, then it should be caching and using the .httr_oauth file that got created and is present in my working directory, shouldn't it?

Yes.

This is mysterious, and I'll need to see it in action.  Perhaps if its in a different folder its not finding the old token.  At any rate, although not finding the cause I think if you make the token, save that token to a safe place then specify that file location in your `GA_AUTH_FILE` value in `.Renviron` that is the safest way to run it.

**Comment by MarkEdmondson1234** [comment] 2017-09-25 10:55
@gilliganondata did you ever get to the bottom of this?

**Comment by gilliganondata** [comment] 2017-09-25 11:50
I'm afraid it still seems to crop up more often than not. With new projects, I've followed the code snippets in Donal Phipp's video -- https://www.youtube.com/watch?v=4B88dRbwNfc -- to the letter. And, yet, more often than not, once a few hours has elapsed with any project, I get the exact same two errors as in the initial issue entry in this thread.

I played around a bit with having the .httr_oauth file in a single spot and then using a GA_AUTH_FILE value in .Renviron that I read, but that was causing more hassles -- as I'd get errors, I was never sure if I hadn't set things properly to go look where I'd told it to or, rather, if the underlying issue was still trumping those efforts.

No one else seems to be chiming in that they've run into this, which makes me think that it's something goofy in my individual setup. I'm _pretty_ sure I'm seeing it on two different machines, but I haven't had the vigilance to fully track that.

It's an easy enough workaround to just delete the .httr-oauth file in my working directory when it crops up.

**Comment by MarkEdmondson1234** [comment] 2017-09-25 14:24
Are you only doing google analytics fetches in the folder, or mixing it up with other API libraries?

**Comment by gilliganondata** [comment] 2017-09-25 16:49
Just GA. Good question -- I think you were thinking I was having tokens step on each other from different OAuth calls from different packages, but that's not the case.

**Comment by MarkEdmondson1234** [comment] 2017-10-06 19:34
This commit (https://github.com/MarkEdmondson1234/googleAnalyticsR/commit/ef34916509be0c92c2909886916b938941d03865) lets you set the auth token, client_id and client_secret in your `.Renvion`file directly.  I'll be interested in if this helps your issue here.  I also changed some logic in `googleAuthR` that may help (e.g. it will always now renew from a file) so updating to the GitHub version of that may help too.

**Comment by MarkEdmondson1234** [comment] 2017-11-16 20:23
This should be all fixed now, with all the recent updates.  Reopen if not so.

**Closed by MarkEdmondson1234** 2017-11-16 20:23 UTC
