### ISSUE TITLE
Dimension filter and "antisample = True" clause.

### ISSUE THREAD

**Issue by PperezMa** [MarkEdmondson1234/googleAnalyticsR#228] opened 2019-01-28 15:39 UTC
Hi, first, thank you for the package it is a great time saver. 

## What goes wrong
When I run an API call for several ViewIds with a dimension filter the "anti_sample = TRUE" clause gets ignored and get to the limit of 1000 rows.  

## Steps to reproduce the problem

```
ga_auth()

my_accounts = ga_account_list()
View(my_accounts)


viewId = c(id2, id1, id2, id3, id4, id5, id6)
ga_data_final = data.frame()


my_dim_filter_object = dim_filter("landingPagePath", operator ="REGEX", expressions = "pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen")
my_dim_filter_clause = filter_clause_ga4(list(my_dim_filter_object), operator = "AND")


orderObject = order_type("sessions", sort_order = ("DESCENDING"))


for (i in viewId) {
  ga_data_temp =
    google_analytics(i,
                     date_range = c("2018-12-01", "2019-01-10"),
                     metrics = c("sessions" , "goal1Completions"),
                     dimensions =c("date", "landingPagePath", "sourceMedium"),
                     order = orderObject,
                     dim_filters = my_dim_filter_clause)
                     anti_sample = TRUE
  
  ga_data_temp$viewId = i
  ga_data_final = rbind(ga_data_final, ga_data_temp)
}

```

## Expected output
> Downloaded [2183] rows from a total of [2183].
> Downloaded [699] rows from a total of [699].
> Downloaded [1035] rows from a total of [1035].
> Downloaded [473] rows from a total of [473].
> Downloaded [194] rows from a total of [194].
> Downloaded [927] rows from a total of [927].
> Downloaded [266] rows from a total of [266].

## Actual output
> Downloaded [1000] rows from a total of [2183].
> Downloaded [699] rows from a total of [699].
> Downloaded [1000] rows from a total of [1035].
> Downloaded [473] rows from a total of [473].
> Downloaded [194] rows from a total of [194].
> Downloaded [927] rows from a total of [927].
> Downloaded [266] rows from a total of [266].

## Session Info
locale:
[1] LC_COLLATE=English_Europe.1252  LC_CTYPE=English_Europe.1252    LC_MONETARY=English_Europe.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Europe.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2         stringi_1.2.4          googleAnalyticsR_0.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        bindr_0.1.1       magrittr_1.5      tidyselect_0.2.5  R6_2.2.2          rlang_0.3.0.1    
 [7] httr_1.3.1        dplyr_0.7.8       tools_3.4.2       googleAuthR_0.7.0 openssl_0.9.7     yaml_2.2.0       
[13] assertthat_0.2.0  digest_0.6.12     tibble_1.4.2      purrr_0.2.5       tidyr_0.8.1       curl_3.0         
[19] memoise_1.1.0     glue_1.3.0        compiler_3.4.2    pillar_1.2.1      jsonlite_1.5      pkgconfig_2.0.1

**Comment by MarkEdmondson1234** [comment] 2019-01-31 19:24
Hmm thanks, will try to reproduce.  It should be the case that using anti_sample=TRUE will always return all results.

**Comment by MarkEdmondson1234** [comment] 2019-01-31 19:35
Is that all the output you get?  I can't see if the calls are actually sent to the anti_sample functons.  Could you rerun and give the output after you set `options(googleAuthR.verbose=2)`

**Comment by PperezMa** [comment] 2019-02-01 16:00
Hello,

Find below ouput with verbose setting here. I hope the format is not too messy to read.

Thank you for looking into it  👍 

--------

> options(googleAuthR.verbose=2)
> #Packages loading
> library(googleAnalyticsR)
2019-02-01 16:52:04> Default Google Project for googleAnalyticsR is now set.  
 This is shared with all googleAnalyticsR users. 
 If making a lot of API calls, please: 
 1) create your own Google Project at https://console.developers.google.com 
 2) Activate the Google Analytics Reporting API 
 3) set options(googleAuthR.client_id) and options(googleAuthR.client_secret) 
 4) Reload the package.
2019-02-01 16:52:04> Set API cache
2019-02-01 16:52:04> No environment argument found, looked in GA_AUTH_FILE
Warning message:
package ‘googleAnalyticsR’ was built under R version 3.4.4 
> library(stringi)
Warning message:
package ‘stringi’ was built under R version 3.4.4 
> 
> 
> #GA API login
> ga_auth()
2019-02-01 16:52:05> No local token found in session
2019-02-01 16:52:05> Auto-refresh of token not possible, manual re-authentication required
Scopes: https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/analytics.readonly https://www.googleapis.com/auth/analytics.manage.users.readonly https://www.googleapis.com/auth/analytics.edit https://www.googleapis.com/auth/analytics.manage.users
App key: XXXXXXXXXXXX-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
Method: new_token
> 
> my_accounts = ga_account_list()
2019-02-01 16:52:05> Skipping token checks as using cache
2019-02-01 16:52:05> Request: https://www.googleapis.com/analytics/v3/management/accountSummaries/
2019-02-01 16:52:05> Making new cache
Auto-refreshing stale OAuth token.
2019-02-01 16:52:06> Forgetting cache
Warning message:
package ‘bindrcpp’ was built under R version 3.4.4 
> View(my_accounts)
> 
> #loading view ids for the "for" loop
> viewId = c(id1, id2, id3, id4, id5, id5, id5, id5)
> ga_data_final = data.frame()
> 
> 
> my_dim_filter_object = dim_filter("landingPagePath", operator ="REGEX", expressions = "pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen")
> my_dim_filter_clause = filter_clause_ga4(list(my_dim_filter_object), operator = "AND")
> 
> 
> orderObject = order_type("sessions", sort_order = ("DESCENDING"))
> 
> 
> 
> 
> 
> for (i in viewId) {
+     tryCatch({
+         ga_data_temp =
+             google_analytics(i,
+                              date_range = c("2018-12-01", "2019-01-10"),
+                              metrics = c("sessions" , "goal1Completions"),
+                              dimensions =c("date", "landingPagePath", "sourceMedium"),
+                              order = orderObject,
+                              dim_filters = my_dim_filter_clause)
+         anti_sample = TRUE
+         
+         ga_data_temp$viewId = i
+         ga_data_final = rbind(ga_data_final, ga_data_temp)
+     }, error=function(e){})
+ }
2019-02-01 16:52:06> Calling APIv4....
2019-02-01 16:52:06> Single v4 batch
2019-02-01 16:52:09> Skipping token checks as using cache
2019-02-01 16:52:09> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-02-01 16:52:09> Making new cache
2019-02-01 16:52:09> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:108015270","dateRanges":[{"startDate":"2018-12-01","endDate":"2019-01-10"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"},{"name":"ga:landingPagePath"},{"name":"ga:sourceMedium"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"},{"expression":"ga:goal1Completions","alias":"goal1Completions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"dimensionFilterClauses":{"operator":"AND","filters":[{"dimensionName":"ga:landingPagePath","not":false,"operator":"REGEXP","expressions":["pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen"],"caseSensitive":false}]},"orderBys":{"fieldName":"ga:sessions","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
2019-02-01 16:52:15> Downloaded [1000] rows from a total of [2183].
2019-02-01 16:52:16> Calling APIv4....
2019-02-01 16:52:16> Single v4 batch
2019-02-01 16:52:16> Skipping token checks as using cache
2019-02-01 16:52:16> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-02-01 16:52:16> Making new cache
2019-02-01 16:52:16> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:114887353","dateRanges":[{"startDate":"2018-12-01","endDate":"2019-01-10"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"},{"name":"ga:landingPagePath"},{"name":"ga:sourceMedium"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"},{"expression":"ga:goal1Completions","alias":"goal1Completions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"dimensionFilterClauses":{"operator":"AND","filters":[{"dimensionName":"ga:landingPagePath","not":false,"operator":"REGEXP","expressions":["pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen"],"caseSensitive":false}]},"orderBys":{"fieldName":"ga:sessions","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
2019-02-01 16:52:18> Downloaded [699] rows from a total of [699].
2019-02-01 16:52:18> Calling APIv4....
2019-02-01 16:52:18> Single v4 batch
2019-02-01 16:52:18> Skipping token checks as using cache
2019-02-01 16:52:18> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-02-01 16:52:18> Making new cache
2019-02-01 16:52:18> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:114865754","dateRanges":[{"startDate":"2018-12-01","endDate":"2019-01-10"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"},{"name":"ga:landingPagePath"},{"name":"ga:sourceMedium"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"},{"expression":"ga:goal1Completions","alias":"goal1Completions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"dimensionFilterClauses":{"operator":"AND","filters":[{"dimensionName":"ga:landingPagePath","not":false,"operator":"REGEXP","expressions":["pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen"],"caseSensitive":false}]},"orderBys":{"fieldName":"ga:sessions","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
2019-02-01 16:52:21> Downloaded [1000] rows from a total of [1035].
2019-02-01 16:52:21> Calling APIv4....
2019-02-01 16:52:21> Single v4 batch
2019-02-01 16:52:21> Skipping token checks as using cache
2019-02-01 16:52:21> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-02-01 16:52:21> Making new cache
2019-02-01 16:52:21> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:116710236","dateRanges":[{"startDate":"2018-12-01","endDate":"2019-01-10"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"},{"name":"ga:landingPagePath"},{"name":"ga:sourceMedium"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"},{"expression":"ga:goal1Completions","alias":"goal1Completions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"dimensionFilterClauses":{"operator":"AND","filters":[{"dimensionName":"ga:landingPagePath","not":false,"operator":"REGEXP","expressions":["pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen"],"caseSensitive":false}]},"orderBys":{"fieldName":"ga:sessions","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
2019-02-01 16:52:22> Downloaded [473] rows from a total of [473].
2019-02-01 16:52:22> Calling APIv4....
2019-02-01 16:52:22> Single v4 batch
2019-02-01 16:52:22> Skipping token checks as using cache
2019-02-01 16:52:22> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-02-01 16:52:22> Making new cache
2019-02-01 16:52:22> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:116695661","dateRanges":[{"startDate":"2018-12-01","endDate":"2019-01-10"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"},{"name":"ga:landingPagePath"},{"name":"ga:sourceMedium"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"},{"expression":"ga:goal1Completions","alias":"goal1Completions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"dimensionFilterClauses":{"operator":"AND","filters":[{"dimensionName":"ga:landingPagePath","not":false,"operator":"REGEXP","expressions":["pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen"],"caseSensitive":false}]},"orderBys":{"fieldName":"ga:sessions","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
2019-02-01 16:52:23> Downloaded [194] rows from a total of [194].
2019-02-01 16:52:23> Calling APIv4....
2019-02-01 16:52:23> Single v4 batch
2019-02-01 16:52:23> Skipping token checks as using cache
2019-02-01 16:52:23> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-02-01 16:52:23> Making new cache
2019-02-01 16:52:23> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:114912413","dateRanges":[{"startDate":"2018-12-01","endDate":"2019-01-10"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"},{"name":"ga:landingPagePath"},{"name":"ga:sourceMedium"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"},{"expression":"ga:goal1Completions","alias":"goal1Completions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"dimensionFilterClauses":{"operator":"AND","filters":[{"dimensionName":"ga:landingPagePath","not":false,"operator":"REGEXP","expressions":["pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen"],"caseSensitive":false}]},"orderBys":{"fieldName":"ga:sessions","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
2019-02-01 16:52:26> Downloaded [927] rows from a total of [927].
2019-02-01 16:52:26> Calling APIv4....
2019-02-01 16:52:26> Single v4 batch
2019-02-01 16:52:26> Skipping token checks as using cache
2019-02-01 16:52:26> Request: https://analyticsreporting.googleapis.com/v4/reports:batchGet/
2019-02-01 16:52:26> Making new cache
2019-02-01 16:52:26> Body JSON parsed to: {"reportRequests":[{"viewId":"ga:114883257","dateRanges":[{"startDate":"2018-12-01","endDate":"2019-01-10"}],"samplingLevel":"DEFAULT","dimensions":[{"name":"ga:date"},{"name":"ga:landingPagePath"},{"name":"ga:sourceMedium"}],"metrics":[{"expression":"ga:sessions","alias":"sessions","formattingType":"METRIC_TYPE_UNSPECIFIED"},{"expression":"ga:goal1Completions","alias":"goal1Completions","formattingType":"METRIC_TYPE_UNSPECIFIED"}],"dimensionFilterClauses":{"operator":"AND","filters":[{"dimensionName":"ga:landingPagePath","not":false,"operator":"REGEXP","expressions":["pf2019|crea-biglietto-auguri-buon-natale-capodanno|ujevi-jokivansag|envie-votos-de-boas-festas|greeting-by-web|festliche-vorlagen"],"caseSensitive":false}]},"orderBys":{"fieldName":"ga:sessions","orderType":"VALUE","sortOrder":"DESCENDING"},"pageToken":"0","pageSize":1000,"includeEmptyRows":true}]}
2019-02-01 16:52:27> Downloaded [266] rows from a total of [266].
>

**Comment by MarkEdmondson1234** [comment] 2019-09-06 13:13
Sorry its taken so long to answer this one, but it looks like in your loop you are not actually calling anti_sample (or setting max) so you get the default 1000 rows:

```r
for (i in viewId) {
     tryCatch({
         ga_data_temp =
             google_analytics(i,
                             date_range = c("2018-12-01", "2019-01-10"),
                              metrics = c("sessions" , "goal1Completions"),
                              dimensions =c("date", "landingPagePath", "sourceMedium"),
                              order = orderObject,
                              dim_filters = my_dim_filter_clause)  
### THIS IS NOT IN THE FUNCTION ####
         anti_sample = TRUE
         
         ga_data_temp$viewId = i
         ga_data_final = rbind(ga_data_final, ga_data_temp)
     }, error=function(e){})
 }
```

As such I don't think this is an error with the library, so closing.

**Closed by MarkEdmondson1234** 2019-09-06 13:13 UTC
Labels: bug
