### ISSUE TITLE
Passing `ganalytics`-style expressions fails for dimension and metric filters

### ISSUE THREAD

**Issue by mattpolicastro** [MarkEdmondson1234/googleAnalyticsR#339] opened 2020-11-13 23:34 UTC
## What goes wrong
When using the `ganalytics` package's expression functions to filter dimensions or metrics as demonstrated in the [docs](https://code.markedmondson.me/googleAnalyticsR/articles/ganalytics.html), an error is thrown stating that the S4 (e.g. `orExpr`, `andExpr`) class can't be coerced to a vector.

## Steps to reproduce the problem

1. Write a basic Google Analytics query using the `google_analytics` function.
2. Pass a `ganalytics`-generated filter expression as either the `dim_filters`or `met_filters` function parameters.

## Expected output

A standard `google_analytics` query response as filtered by the provided expressions.

## Actual output

```
> options(googleAuthR.verbose=2)
> at_least_one_conversion <- Expr(~goalCompletionsAll > 0) | Expr(~transactions > 0)
> 
> google_analytics(
+   viewId = view_id,
+   date_range = c("30daysAgo", "yesterday"),
+   metrics = c("users", "sessions", "goalCompletionsAll"),
+   dimensions = c("deviceCategory", "userType"),
+   met_filters = at_least_one_conversion
+ )
Error in as.list.default(X) : 
  no method for coercing this S4 class to a vector
```

## Session Info

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAnalyticsR_0.8.0 ganalytics_0.10.7     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        compiler_4.0.3    pillar_1.4.6      later_1.1.0.1     googleAuthR_1.3.0 plyr_1.8.6        tools_4.0.3       digest_0.6.26    
 [9] lubridate_1.7.9   jsonlite_1.7.1    memoise_1.1.0     lifecycle_0.2.0   tibble_3.0.4      gargle_0.5.0      pkgconfig_2.0.3   rlang_0.4.8      
[17] cli_2.1.0         rstudioapi_0.11   dplyr_1.0.2       httr_1.4.2        stringr_1.4.0     xml2_1.3.2        generics_0.0.2    vctrs_0.3.4      
[25] fs_1.5.0          tidyselect_1.1.0  glue_1.4.2        R6_2.4.1          fansi_0.4.1       XML_3.99-0.5      tidyr_1.1.2       purrr_0.3.4      
[33] selectr_0.4-2     magrittr_1.5      scales_1.1.1      promises_1.1.1    ellipsis_0.3.1    assertthat_0.2.1  rvest_0.3.6       colorspace_1.4-1 
[41] httpuv_1.5.4      stringi_1.5.3     lazyeval_0.2.2    munsell_0.5.0     crayon_1.3.4 
```

**Comment by MarkEdmondson1234** [comment] 2020-11-16 08:19
Thanks I need help from @jdeboer with this one

**Comment by jdeboer** [comment] 2020-11-18 11:23
Ok, I'll take a look over the weekend and see if I can indentify the cause.

**Comment by jdeboer** [comment] 2020-11-20 22:04
Hi @MarkEdmondson1234 , it's been a while since I've worked on either of these projects (ganalytics or googleAnalyticsR) so I'm in the process of setting myself up and running through the builds. I am getting this error when building the vignettes which I believe relates to where googleAnalyticsR saves its authentication token: `Path '~/ga.oauth' does not exist`. This occurs on this line: `ga_auth(file.path("~", "ga.oauth"))`. Was there a change to how authentication works in googleAnalyticsR that I need to reflect in the vignette? Is the token saved somewhere else now, or what do I need to do to create this file?

**Comment by jdeboer** [comment] 2020-11-20 22:18
@mattpolicastro , thanks for reporting the error. Could you please rerun your example above and then run `traceback()` immediately after you get the error message. This will give details about where in the package (googleAnalyticsR or ganalytics) the error is occurring. Please copy and paste the results of the traceback here and hopefully that will help us get the bottom of this more quickly. Thanks.

**Comment by jdeboer** [comment] 2020-11-20 23:11
@MarkEdmondson1234 , I think this is related to or caused by https://github.com/MarkEdmondson1234/googleAnalyticsR/commit/5195e9046792ed9aa5a77eb2e861a784ad55d5e9#diff-a254a76d5944e8ac1832739ef1198e41cbb77e9eaff84ebbd2dee60d108a37f9

**Comment by jdeboer** [comment] 2020-11-20 23:45
Undoing some of the changes from the above commit might resolve this, but that would reintroduce issue https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/253. The workaround to #253 was to run `class(my_segments_list) <- "segment_ga4"` immediately after creating the googleAnalyticsR segments list, which isn't ideal so I proposed a couple of options for a more permanent fix, which included to either:
1.  Define a new class in googleAnalyticsR specifically for a list of `segment_ga4` objects that is separate from an atomic `segment_ga4` object (e.g. call it something like `segments_ga4` if that class name is not already in use), and create a function in googleAnalyticsR that users can call to create such a list object (e.g. `create_segments_list()`) rather than requiring users to call `my_segments_list <- list(segment1, segment2)` and `class(my_segments_list) <- 'segment_ga4'` directly.
2. Modify googleAnalyticsR to examine the elements of a supplied `segments` list to determine whether all of the elements are of the class `segment_ga4`, and if so call `class(segments) <- "segment_ga4"` on that object.

Personally, I feel that option 2 feels a little hacky, but the most convienent for users as they wouldn't need to modify their exiting code. Option 1 on the other hand feels like a more robust solution but would unfortunately require end users to update their code to call the new function instead of calling `list()`.

**Comment by jdeboer** [comment] 2020-11-20 23:49
@MarkEdmondson1234 , or perhaps we could do both options 1 and 2 above, where we issue a message/warning to users who continue using `list()` to switch to using `create_segments_list()` (or whatever we decide to call it) instead.

**Comment by jdeboer** [comment] 2020-11-21 00:29
Just realised this issue is in relation to filters, not segments, but I think the same general solution will apply.

**Comment by jdeboer** [comment] 2020-11-22 23:20
Having read through the googleAnalyticsR's source code, I think the issue is with the definition of a function named [`add_class_if_list` located here](https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/utilities.R#L25). 

Currently it is defined as:
```r
add_class_if_list <- function(x, the_class){
  if(!is.null(x) && class(x) == "list"){
    class(x) <- the_class
  }
  x
}
```

I think this needs to be changed to:
```r
add_class_if_list <- function(x, the_class){
  if(!is.null(x) && class(x) == "list"){
    x <- as(x, the_class)
  }
  x
}
```

I'm not sure what the purpose is of the condition `&& class(x) == "list"`, so perhaps if that's unnecessary then it could be simplified to:
```r
add_class_if_list <- function(x, the_class){
  if(!is.null(x)){
    as(x, the_class)
  }
}
```

`as` calls whichever method is available to coerce the object into the required class. Directly setting the class using `class<-` does not do that but instead just leaves the object as it was and relabels the class attribute of that object - it doesn't do anything to check the validity of the object. This is why above I propose to use the `as` function.

However, perhaps we also need to do something similar to what we do with segments by calling `assign_list_class` where if a list is provided containing objects belonging to the `.filter_clauses_ga4` class, then the list is coerced into an object of the appropriate class (or simply labelled with the appropriate class name)? I'm still in the process of setting up the googleAnalyticsR build on my machine, so once I've got that up and running I'll try out the above change and will see what else (if anything) needs to happen with this last point.

**Comment by jdeboer** [comment] 2020-11-23 10:21
I've committed changes to my fork of googleAnalyticsR that appears to have fixed this issue and passes the following tests:
```r
at_least_one_conversion <- Expr(~goalCompletionsAll > 0) | Expr(~transactions > 0)
google_analytics(
   viewId = view_id,
   date_range = c("30daysAgo", "yesterday"),
   metrics = c("users", "sessions", "goalCompletionsAll"),
   dimensions = c("deviceCategory", "userType"),
   met_filters = at_least_one_conversion
)
```
```r
#' ## create filters on metrics
mf <- met_filter("bounces", "GREATER_THAN", 0)
mf2 <- met_filter("sessions", "GREATER", 2)
#'
#' ## create filters on dimensions
df <- dim_filter("source","BEGINS_WITH","1",not = TRUE)
df2 <- dim_filter("source","BEGINS_WITH","a",not = TRUE)
#'
#' ## construct filter objects
fc2 <- filter_clause_ga4(list(df, df2), operator = "AND")
fc <- filter_clause_ga4(list(mf, mf2), operator = "AND")
#'
#' ## make v4 request

google_analytics(view_id,
                 date_range = c("30daysAgo", "yesterday"),
                 dimensions=c('source','medium'),
                 metrics = c('sessions','bounces'),
                 met_filters = fc,
                 dim_filters = fc2,
                 filtersExpression = "ga:source!=(direct)")
```
```r
#' ## create filters on dimensions
df <- dim_filter("source","BEGINS_WITH","1",not = TRUE)
df2 <- dim_filter("source","BEGINS_WITH","a",not = TRUE)
df3 <- dim_filter("medium","EXACT","organic")

#'
#' ## construct filter objects
fc <- filter_clause_ga4(list(mf, mf2), operator = "AND")
fc2 <- filter_clause_ga4(list(df, df2), operator = "AND")
fc3 <- filter_clause_ga4(list(df3))
#'
#' ## make v4 request

google_analytics(view_id,
                 date_range = c("30daysAgo", "yesterday"),
                 dimensions=c('source','medium'),
                 metrics = c('sessions','bounces'),
                 met_filters = fc,
                 dim_filters = list(fc2,fc3),
                 filtersExpression = "ga:source!=(direct)")
```
I will submit a pull request.

**Closed** 2020-11-24 19:41 UTC
Labels: bug, help wanted

**Comment by MarkEdmondson1234** [comment] 2020-11-24 19:45
Thanks for all the work!  I'll merge it as the GA4 stuff is also in the works so tests etc will be running soon, aiming for a v0.9 release in next few months.

**Comment by mattpolicastro** [comment] 2020-11-25 02:02
@jdeboer @MarkEdmondson1234 apologies for not responding sooner—looks like the fix is in, so presumably no need for a session traceback?

Also, thank you both for jumping on this!

**Comment by MarkEdmondson1234** [comment] 2020-11-25 15:42
@mattpolicastro - no worries, can you test it works with you?  You will need the GitHub latest version installed via `remotes::install_github("MarkEdmondson1234/googleAnalyticsR")`

**Comment by mattpolicastro** [comment] 2020-12-03 06:39
@MarkEdmondson1234 again, sorry for being slow on the uptake. Everything seems to be running smoothly with a few iterations on test queries from a known source so I'd say this is good to go for now. Thanks again!

**Comment by MarkEdmondson1234** [comment] 2020-12-03 08:00
@mattpolicastro No worries, thanks for checking!  This then will be in the next CRAN release 0.9.0
